import React from 'react'
import Breadcrumb from '../../components/Breadcrumb'

function index() {
  return (
    <>

        <Breadcrumb heading="Admission Policy" />

        <div className="container">
            <div className="row">
                <div className="col-sm-12 pt-4">
                    <p className=" txt-justi my-para">
                        Admission in the Institute are taken as per guidelines given by JEECUP and BTEUP.

                        Candidates get admission in Polytechnics through counselling after qualifying the
                        Entrance Examination conducted by Joint Entrance Examination Council (JEECUP), Lucknow. All the
                        reservations are effective as per UP government rules. For Courses, Qualification &amp; other
                        details refer to <a href="http://www.jeecup.nic.in" style={{color:"#f46c22"}} target="_blank">http://www.jeecup.nic.in</a>
                    </p>
                </div>
            </div>


            <div className="row">
                <div className="col-sm-12 pt-4 pb-4 table-responsive">
                    <table className="table text-center table-bordered table-hover">

                        <tbody>
                            <tr>
                                <td>Entrance Examination (JEECUP) from filling Months :</td>
                                <td>January and Fabruary Every Year</td>
                            </tr>
                            <tr>
                                <td>Entrance Examination Date :</td>
                                <td>Last week of april</td>
                            </tr>
                            <tr>
                                <td>Result of Entrance Examination :</td>
                                <td>Mid of May</td>
                            </tr>
                            <tr>
                                <td>Counselling for admission :</td>
                                <td>June and July</td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>



            <div className="row">
                <div className="col-sm-12">
                    <p className=" txt-justi my-para">
                        <strong>Documents required :</strong><br/>
                        Following documents are required for first year student Admission:
                    </p>
                    <ul>
                        <li>Allotment letter generated by JEECUP counselling.</li>
                        <li>Fee draft in favour of <strong>Government Polytechnic, Mohammadi Kheri</strong> payable at college.</li>
                        <li>Self-attested photocopies of educational qualification certificates such as high school,
                            intermediate, graduation, etc. and other such as Aadhar card, Caste certificate, Income
                            certificate and Domicile certificate.</li>
                        <li>Original transfer certificate, migration certificate, character certificate of last
                            institution and medical fitness certificate from CMO of any government district hospital.
                        </li>
                        <li>Gap certificate. (if any)</li>
                    </ul>
                </div>
            </div>


            <div className="row">
                <div className="col-sm-12">
                    <p className=" txt-justi my-para">
                        <strong>Document Rentention Policy :</strong> <br/>
                        We do not submit any original educational certificate at the time of admission.
                    </p>

                </div>
            </div>




        </div>
    </>
  )
}

export default index